info/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from info import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT})
]

staff/urls.py
from django.conf.urls import url

from staff import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^edit/$', views.EditView.as_view(), name='edit'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

staff/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

# Create your models here.
class User(AbstractUser):
    address = models.CharField(max_length=50,null=True,blank=True)
    mobile = models.IntegerField(default=1)
    image = models.ImageField(upload_to='user')


    objects = UserManager()

    def __str__(self):
        return self.first_name

staff/forms.py
from django import forms


from staff.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=40)
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password']
class EditForm(forms.ModelForm):
    email = forms.CharField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name','address','image','mobile','password2','password1')

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        print "password1",password1
        print "password2",password2

        if password1 and password2 and password1 == password2:
            return password2
        else:
            raise forms.ValidationError('password_mismatch')

    def save(self, commit=True):
        form = super(EditForm, self).save(commit=False)
        if commit:
            form.set_password(self.cleaned_data["password2"])
            form.save()

        return form

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(max_length=18, widget=forms.PasswordInput)
    email = forms.CharField(required=True)
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password','password1','address','image','mobile']

    def clean_password1(self):
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')
        if not password1:
            raise forms.ValidationError("You must confirm your password")
        if password != password1:
            raise forms.ValidationError("Your passwords do not match")
        return password1

    def save(self, commit=True):
        form = super(RegistrationForm, self).save(commit=False)
        if commit:
            form.set_password(self.cleaned_data["password"])
            form.save()
        return form

staff/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

# Create your views here.
from django.views import generic

from staff.forms import LoginForm, EditForm, RegistrationForm
from staff.models import User


class LoginView(generic.FormView):
    template_name = 'account/login.html'
    model = User
    form_class = LoginForm
    success_url = 'edit'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            return redirect(".")
        else:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)


class EditView(generic.UpdateView):
    template_name = 'edit.html'
    model = User
    form_class = EditForm
    success_url = '/'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        return super(EditView, self).form_valid(form)


class HomeView(generic.FormView):
    template_name = 'index.html'
    form_class = RegistrationForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super(HomeView, self).form_valid(form)


class LogoutView(generic.RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

templates/edit.html
<!DOCTYPE html>
{% load static %}
<html >

<head>

  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">


      <link rel="stylesheet" href="{% static 'css/style.css' %}"/>


</head>

<body>
  <div class="form">
        <div id="signup">
          <a href="{% url 'staff:logout' %}"> Logout</a>
          <h1>Edit Profile</h1>

          <form action="{% url 'staff:edit' %}" method="post">
            {% csrf_token %}

          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <!--<input type="text" name="first_name" required autocomplete="off" />-->
              {{ form.first_name }}
              {{form.errors.first_name}}
            </div>

            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <!--<input type="text" name="last_name" required autocomplete="off"/>-->
              {{ form.last_name }}
              {{form.errors.last_name}}
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <!--<input type="email" name="email" required autocomplete="off"/>-->
            {{ form.email }}
            {{form.errors.email}}
          </div>

            <div class="field-wrap">
            <label>
              Username<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.username }}
              {{form.errors.username}}
          </div>
            <div class="field-wrap">
            <label>
              Mobile no<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.mobile }}
              {{form.errors.mobile}}
          </div>
            <div class="field-wrap">
            <label>
              Address<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.address }}
              {{form.errors.address}}
          </div>
            <div class="field-wrap">
            <label>
              Profile photo<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.image }}
              {{form.errors.image}}
          </div>
            <div class="field-wrap">
            <label>
              New password<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.password1 }}
              {{form.errors.password1}}
          </div>
          <div class="field-wrap">
            <label>
              Re password<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.password2 }}
              {{form.errors.password2}}
          </div>
          <button type="submit" class="button button-block" >Get Started</button>


          </form>

        </div>


     <!-- tab-content -->

</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{% static 'js/index.js' %}" ></script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html >

<head>

  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">


      <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

  
</head>

<body>
  <div class="form">
        <div id="signup">   
          <h1>Sign Up for Free</h1>
          
          <form action="{% url 'staff:home' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
          
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <!--<input type="text" name="first_name" required autocomplete="off" />-->
              {{ form.first_name }}
              {{form.errors.first_name}}
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <!--<input type="text" name="last_name" required autocomplete="off"/>-->
              {{ form.last_name }}
              {{form.errors.last_name}}
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <!--<input type="email" name="email" required autocomplete="off"/>-->
            {{ form.email }}
            {{form.errors.email}}
          </div>

            <div class="field-wrap">
            <label>
              Username<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.username }}
              {{form.errors.username}}
          </div>
              <div class="field-wrap">
            <label>
              Address<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.address }}
              {{form.errors.address}}
          </div>
             <div class="field-wrap">
            <label>
              Mobile No<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.mobile }}
              {{form.errors.mobile}}
          </div>
          <div class="field-wrap">
            <label>
              Profile Photo<span class="req">*</span>
            </label>
            <!--<input type="text" name="username" required autocomplete="off"/>-->
              {{ form.image }}
              {{form.errors.image}}
          </div>

          <div class="field-wrap ">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <!--<input type="password" name="password" required autocomplete="off"/>-->
            {{ form.password }}
            {{form.errors.password}}
          </div>

            <div class="field-wrap">
            <label>
              Conform Password<span class="req">*</span>
            </label>
            <!--<input type="password" name="password1" required autocomplete="off"/>-->
              {{ form.password1 }}
              {{form.errors.password1}}
          </div>

          <button type="submit" class="button button-block" >Get Started</button>
          
          </form>

        </div>
        

     <!-- tab-content -->
      
</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{% static 'js/index.js' %}" ></script>

</body>
</html>